---

- hosts: localhost
  # gather_facts: False
  tasks:
    - name: Hello tag example
      debug:
        msg: "Hello!"
      tags:
        - firsttask
      when: ansible_facts['os_family']=="Ubuntu"

    - name: No tag example
      debug:
        msg: "How are you?"
      when: ansible_facts['os_family']=="Ubuntu"

    - name: Goodbye tag example
      debug:
        msg: "Goodbye!"
      tags:
        - thirdtask
      # when: ansible_facts['os_family'] == "CentOS"