---
- name: install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: group tomcat
      ansible.builtin.group:
        name: tomcat group
        state: present
    - name: tomcat installation
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present



        
